version: 2.1
orbs:
  cypress: cypress-io/cypress@1.25.1
executors:
  browsers-chrome75-helsinki-tz:
    docker:
      - image: 'cypress/browsers:node12.6.0-chrome75'
    environment:
      TZ: Europe/Helsinki
workflows:
  build:
    jobs:
      - cypress/install:
          executor: cypress/base-14
          build: 'cd frontend && npm run build' # run a custom app build step
          cache-key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json" }}'
          install-command: 'cd frontend && npm ci'
      - cypress/run:
          executor: browsers-chrome75-helsinki-tz
          browser: chrome
          working_directory: 'frontend'
          requires:
            - cypress/install
          install-command: 'cd ../api && npm ci'
          cache-key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json" }}'
          start: 'cd ../api && npm run ci' # start server before running tests
          wait-on: 'http://localhost:9999 http://localhost:3000'
          command: 'ls dist/ && npm run ci'
