version: 2.1
orbs:
  cypress: cypress-io/cypress@1.25.1
executors:
  browsers-chrome75-Helsinki-TZ:
    docker:
      - image: 'cypress/browsers-chrome75'
    environment:
      TZ: 'Europe/Helsinki'
workflows:
  build:
    jobs:
      - cypress/install:
          executor: cypress/base-14
          build: 'cd frontend && pnpm run build' # run a custom app build step
          cache-key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json" }}'
          install-command: 'curl -L https://unpkg.com/@pnpm/self-installer | node && cd frontend && pnpm install --frozen-lockfile'
      - cypress/run:
          executor: browsers-chrome75-Helsinki-TZ
          browser: chrome
          working_directory: 'frontend'
          requires:
            - cypress/install
          install-command: 'curl -L https://unpkg.com/@pnpm/self-installer | node && cd ../api && pnpm install --frozen-lockfile'
          cache-key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json" }}'
          start: 'cd ../api && pnpm run ci' # start server before running tests
          wait-on: 'http://localhost:9999 http://localhost:3000'
          command: 'ls dist/ && pnpm run ci:test'
