version: 2.1
orbs:
  cypress: cypress-io/cypress@1.25.1
workflows:
  build:
    jobs:
      - cypress/install:
          executor: cypress/base-14
          build: 'cd frontend && pnpm run build' # run a custom app build step
          cache-key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json" }}'
          install-command: 'curl -L https://unpkg.com/@pnpm/self-installer | node && cd frontend && pnpm install'
      - cypress/run:
          executor: cypress/browsers-chrome75
          browser: chrome
          # executor: cypress/base-14
          working_directory: 'frontend'
          requires:
            - cypress/install
          install-command: 'curl -L https://unpkg.com/@pnpm/self-installer | node && cd ../api && pnpm install'
          cache-key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json" }}'
          start: 'cd ../api && pwd && pnpm run ci:app & pnpm run wiremock:external' # start server before running tests (WRONG)
          # start: 'cd ../api && pnpm run ci' # start server before running tests
          wait-on: 'http://localhost:9999 http://localhost:3000'
          command: 'sleep 10 && pnpm run ci:test'
