version: 2.1
orbs:
  cypress: cypress-io/cypress@1.25.1
workflows:
  build:
    jobs:
      - cypress/install:
          executor: cypress/base-14
          build: 'cd frontend && pnpm run build' # run a custom app build step
          cache-key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json" }}'
          install-command: 'curl -L https://unpkg.com/@pnpm/self-installer | node && cd frontend && pnpm install'
      - cypress/run:
          executor: cypress/base-14
          requires:
            - cypress/install
          cache-key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json" }}'
          start: 'cd api && pnpm run ci' # start server before running tests
          wait-on: 'http://localhost:3000'
          command: 'cd frontend && ls && pnpm run ci:test'
          install-command: 'curl -L https://unpkg.com/@pnpm/self-installer | node && cd frontend && pnpm install && cd ../api && pnpm install'
