version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install -G pnpm
            - run: cd frontend/ && pwd && pnpm install
            - run: cd api/ && pwd && pnpm install
            - run: cd api/ && pwd && pnpm run ci
workflows:
  build-and-test:
    jobs:
      - build-and-test
