version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: pwd
            - run: cd frontend
            - run: pwd
            - run: npm install
            - run: pwd
            - run: cd ../api
            - run: pwd
            - run: npm install
            - run: pwd
            - run: npm run ci
workflows:
  build-and-test:
    jobs:
      - build-and-test
